### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by lukemarshall-ab** [CityOfZion/neo-go#282]
Hi @decentralisedkev ,

We have come across this project and love it. We would like to re-use / modify a few components. However,  it is currently unfinished without a clear schema.

- Any reason for discontinued support of this project?

- Are you able to complete the last components and ship?

- What is your preferred channel of communication?

**Comment by decentralisedkev** [comment]
Hi, 

I am a contributor in this project and not the maintainer. I have not set a release tag, however you should be able to sync with the blockchain minus verification. Correct me if I am wrong.

Discontinued support because I have been mostly travelling and my focus at the moment is on projects that require a heavy amount of applied cryptography/ research, so at the moment I am unable to continue due to lack of time. AFAIK there is a NEO 3.0 coming, so this implementation would likely become redundant, could be wrong here too, not updated on the details.

I am on Slack: https://github.com/CityOfZion/standards/blob/master/Introduction.md @kev

**Comment by decentralisedkev** [comment]
Paraphrasing for those not on Slack; it seems that NSPCC is going to maintain neo-go, I'm not aware of the details
